image: gitpod/workspace-full-vnc

ports:
  - port: 6080
    visibility: public
    onOpen: open-browser

  - port: 1593
    onOpen: ignore

  - port: 5900
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true

additionalRepositories:
  - url: https://github.com/FruitfulSystems/FreeCAD-Docker
    checkoutLocation: FreeCAD-Docker

workspaceLocation: FreeCAD-GP/main.code-workspace
